format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
