# A routine check to see if there are any Rust-specific security vulnerabilities in the repo we should be aware of.

name: "Audit"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@master
        with:
          crate: cargo-audit
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
