name: "Build docs"

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Cargo docs
        run: cargo doc --no-deps --document-private-items

      - name: Setup MDBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build MDBook
        run: mdbook build docs/ --dest-dir ../docs-build

      - name: Prepare docs
        run: mv ./target/doc ./docs-build/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs-build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
