name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust-ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test `cargo fmt/check/clippy` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: "always"
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v3

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable

      - uses: Swatinem/rust-cache@664ce0090f15897beb496f9faf2f88e6908c80c4

      - run: |
          cargo fmt --check
          cargo clippy
          cargo test
