name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust-ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Test `cargo fmt/clippy/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: "always"
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894

      - run: |
          cargo fmt --check
          cargo clippy
          cargo test
